name: Export source

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: re-organico-main
          path: .
          include-hidden-files: true
          if-no-files-found: error
